# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cdxb4JSn17UPlfGWF6ih1A5FBqsahJkU
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load data
pd.read_csv("dataset/final_livability.csv")

st.title("🏙️ UrbanNest – Neighborhood Livability Explorer")

bhk = st.selectbox("Select BHK Type", df["bhk"].unique())

filtered = df[df["bhk"] == bhk]

st.subheader("Top Livable Localities")

st.dataframe(
    filtered.sort_values("Livability_Score", ascending=False)[
        ["locality", "Livability_Score"]
    ].head(10)
)

st.subheader("Livability Comparison")

top10 = filtered.sort_values("Livability_Score", ascending=False).head(10)

plt.figure()
plt.bar(top10["locality"], top10["Livability_Score"])
plt.xticks(rotation=45)
st.pyplot(plt)

st.markdown("""
### How Livability Score is Calculated

Livability = 0.6 × Affordability + 0.4 × AQI
""")

